### ISSUE TITLE
Derive private key using sbt-pgp for signing sources

### ISSUE THREAD

**Issue by mdedetrich** [pjfanning/sbt-source-dist#1]
It would be ideal if possible to derive the private key using sbt-pgp. The reasoning behind this is that projects using sbt-source-dist are highly likely to already be using sbt-pgp to publish signed artifacts and in usage sbt-gpg not only do we have a common abstraction for signing but it also enforces that signed jar's will contain the same signature as signed source packages.

**Comment by pjfanning** [comment]
#33 merged
