### ISSUE TITLE
Make sure git checkout is in pristine status

### ISSUE THREAD

**Issue by mdedetrich** [pjfanning/sbt-source-dist#13]
As mentioned in https://github.com/apache/incubator-pekko/pull/143#pullrequestreview-1291162348, this plugin should make sure that the git checkout status is pristine before attempting to create the archive files

**Comment by mdedetrich** [comment]
In regards to the implementation, since its not implied that a user will have `git`, we should also check the existence of `git` (if `git` doesn't exist on path then we can just short circuit as a success).

**Comment by pjfanning** [comment]
https://github.com/sbt/sbt-git may solve these issues
* `set useReadableConsoleGit` appears to get sbt-git to use command line git
* you can then use `git status` via the plugin

I have never used this plugin directly and it may take a little playing with it to get it to work the way we need it to

**Comment by pjfanning** [comment]
I have a check for this in #30
