### ISSUE TITLE
Investigate using `git archive`

### ISSUE THREAD

**Issue by mdedetrich** [pjfanning/sbt-source-dist#14]
The current logic in sbt-source-dist is to manually filter out files specified in `.gitignore` as well as manually construct the archives. It might make sense that rather than doing this, we should use `git archive` (if the machine has git) which should be a lot faster and correct, even if we have to manually end up deflating it for the other archive formats.

We can use https://github.com/sbt/sbt-git to do the heavy lifting, just need to make this plugin extend sbt-git.

**Comment by mdedetrich** [comment]
@jrudolf Regarding the problem you described at https://github.com/apache/incubator-pekko/pull/143#issuecomment-1425456760, I didn't experience this but I suspect because I used it on a clean repo and maybe its including either `target` or something along those lines?

I know that sbt source dist currently doesn't fully support `.gitignore`. It may be quicker to just solve that problem. If you want to work on this issue don't forget to assign yourself.

**Comment by mdedetrich** [comment]
So I haven't been able to replicate this, at least my original theory of `target` getting included turned out to be incorrect

**Comment by pjfanning** [comment]
`git archive` is probably the way forward but there are a few git managed files that we would ideally leave out of the source distribution.
* .gitignore
* .asf.yaml

It's probably not too bad to include these in the source distribution but the existing code leaves them out.

**Comment by mdedetrich** [comment]
`git ls-tree` is another option I believe, with the correct args it can give us a list of files tracked by git and then we can remove the other problematic ones (such as `.gitignore` and `.asf.yaml`).

**Comment by pjfanning** [comment]
#30 merged
