### ISSUE TITLE
change filenames

### ISSUE THREAD

**Issue by pjfanning** [pjfanning/sbt-source-dist#23]
It's been suggested that we change filenames for the zip/tgz - https://lists.apache.org/thread/nyn2kmfhln27vxtybyjq2vb69tk1hjgw

Another project - https://dist.apache.org/repos/dist/dev/incubator/streampark/2.1.1-RC1/
has apache-streampark-2.1.1-incubating-src.tar.gz

We have 
incubating-pekko-src-1.0.0-20230629.tgz

The only rule that I am aware of is that we must have the word 'incubating' in the name.

**Comment by justinmclean** [comment]
That is correct incubating projects can name releases however they like as long as it includes "incubating". Including "apache" may give your project a bit more legal protection and might be a good idea. Including the version number may help your users.

**Comment by pjfanning** [comment]
this is in v0.1.7
