### ISSUE TITLE
only produce tgz files

### ISSUE THREAD

**Issue by pjfanning** [pjfanning/sbt-source-dist#24]
https://lists.apache.org/thread/nyn2kmfhln27vxtybyjq2vb69tk1hjgw suggests only have tgz or zip but not both - other incubator projects seem to prefer tgz (or tar.gz - the same format but the name is more explicit about tar and gz)

**Comment by justinmclean** [comment]
The project can do what they want here, there is no ASF requirement. The question to ask is what's best for people who use or view the releases.

**Comment by pjfanning** [comment]
#32 merged
